### ISSUE TITLE
Upgrade from 6.6.0.0 to 7.0.4.0 stops forums list from displaying anything

### ISSUE THREAD

**Issue by puresystems** [DNNCommunity/Dnn.CommunityForums#243] opened 2023-02-22 12:25 UTC
## Describe the bug
Upgraded a test site from 6.6.0.0 to 7.0.4.0 and now none of the forums are displayed on the main Forums page. They exist in the control panel.

## Software Versions
- DNN: 9.10.2
- Module: 7.0.4

## To Reproduce
1. Upgrade module from 6.6.0.0 to 7.0.4.0 using the installer
2. View existing Forums page where the module is set to Standard Mode and ForumView template

## Expected behavior
The existing forums should be displayed in list format.

## Screenshots
N/A

## Error log
No errors are logged in DNN log viewer or log files.

## Additional context
After doing a bit more digging, running SQL profiler when the page first loads does show this query:

`exec dbo.activeforums_UI_ForumView @PortalId=0,@ModuleId=649,@UserId=10,@IsSuperUser=0,@ParentForumId=-1,@ForumIds=N'10;21;25;'`

Which does return results when i run it in SQL.

So it might be a templating issue maybe?

**Comment by johnhenley** [comment] 2023-02-22 12:56
Hi @puresystems thanks for the issue. Can you change forum display to "default" and see if that displays the forums?

**Comment by puresystems** [comment] 2023-02-22 14:25
Hi @johnhenley - we've changed the display but it hasn't seemed to help. Interestingly, the quick forum nav drop-down doesn't contain the forums accessible and i can use this to see forum posts which work, it's just the initial Forums view which isn't working.

**Comment by johnhenley** [comment] 2023-02-22 15:00
> Hi @johnhenley - we've changed the display but it hasn't seemed to help. Interestingly, the quick forum nav drop-down doesn't contain the forums accessible and i can use this to see forum posts which work, it's just the initial Forums view which isn't working.

Are you saying the quick forum nav drop down is or isn't working?

**Comment by johnhenley** [comment] 2023-02-22 15:01
What is your URL for the forums page? 
add /aff/10 to the URL and see if you see the topics list for that forum.

**Comment by puresystems** [comment] 2023-02-22 16:36
> 

Sorry, it should have read that the Quick Nav DOES show contain  the forums.

**Comment by johnhenley** [comment] 2023-02-22 17:13
> > 
> 
> 
> 
> Sorry, it should have read that the Quick Nav DOES show contain  the forums.

Ok. That's good since it means at least the module is loading. And you're seeing content on specific forum pages, correct?

**Comment by johnhenley** [comment] 2023-02-22 18:38
What theme are you using? Can you test the _default theme if haven't already?

**Comment by johnhenley** [comment] 2023-02-22 19:00
Also, a screenshot of the /templates folder under whatever theme you are currently using.

**Comment by johnhenley** [comment] 2023-02-22 19:00
And just to make sure, can you check this setting for forum group and forums?
![image](https://user-images.githubusercontent.com/9553126/220731950-bad9534b-75c0-400d-b370-c702c0544ce7.png)

**Comment by WillStrohl** [comment] 2023-02-22 19:38
Hello @puresystems ... Thank you for reporting this issue. DId this also happen in the Release Candidate, or are you just now attempting the upgrade?

**Comment by puresystems** [comment] 2023-02-23 09:32
@johnhenley @WillStrohl Ok, it appears to be the Hidden option for the Groups which was causing this. By making the Groups unhidden, it now shows the accessible forums to the user. I guess the behaviour may have changed with this. I think previously, if we didn't Hide the groups, then a user would see all the group Headings but not the forums if they didn't have access to them. Thanks for your help.

**Comment by johnhenley** [comment] 2023-02-23 11:50
> @johnhenley @WillStrohl Ok, it appears to be the Hidden option for the Groups which was causing this. By making the Groups unhidden, it now shows the accessible forums to the user. I guess the behaviour may have changed with this. I think previously, if we didn't Hide the groups, then a user would see all the group Headings but not the forums if they didn't have access to them. Thanks for your help.

Interesting. I think the way you had it set up is the intended behavior so this might be a bug. I will do some investigating and report back.

**Comment by WillStrohl** [comment] 2023-02-23 15:53
Thank you both, @johnhenley & @puresystems ... We definitely don't intend to release a breaking change like this in a version of this context.  :(

**Comment by johnhenley** [comment] 2023-02-23 17:15
Looks like this was actually a bug introduced when the project was converted from VB.Net to C#, but it only surfaced after the integration with Active Social was removed in 07.00.04. Long story short, I have a pull request waiting, and @WillStrohl can decide if it should go into the current 07.00.05 RC or how to release it.

**Comment by WillStrohl** [comment] 2023-02-23 17:52
@johnhenley What are the impacts from your perspective on including this bug fix in 7.0.5 RC versus waiting until 7.0.6?

**Comment by johnhenley** [comment] 2023-02-23 18:19
> @johnhenley What are the impacts from your perspective on including this bug fix in 7.0.5 RC versus waiting until 7.0.6?  

I don't know how many use that feature but it should be able to wait as long as it has been identified, there is a workaround, and fix is in next release. @puresystems do you agree?

**Comment by puresystems** [comment] 2023-02-24 09:07
@johnhenley We don't mind waiting as it's not affecting live sites yet as we've not upgraded these yet.

**Closed** 2023-03-28 23:31 UTC
Labels: bug
