### ISSUE TITLE
BUG: Alignment issues on `Active Topics` filtered list

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/Dnn.CommunityForums#948] opened 2024-07-02 04:56 UTC
## Describe the bug
When viewing `Active Topics` filtered list, there are content alignment issues.

## Software Versions
- DNN: 09.13.03
- Module: 08.01.00

## To Reproduce
1. Filter by `Active Topics`
2. See alignment issues (screenshot below)

## Expected behavior
Alignment should be consistent with other lists.

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4568451/013e55b8-7506-4969-85e5-8ca7a934560b)

## Error log
n/a

## Additional context
n/a

**Comment by Timo-Breumelhof** [comment] 2024-07-02 08:08
@johnhenley These are not form a template currently are they?
I'll just put in some CSS for the width and in v9 I'll re-do a template?

BTW, I also noticed there are no headings for the table #949

**Comment by Timo-Breumelhof** [comment] 2024-07-02 08:17
@johnhenley The main issue here is that it generated a table in a  table and not "connected columns"

**Comment by Timo-Breumelhof** [comment] 2024-07-02 08:33
Note to self, this will make the table render better but there's stil the issue of the columns not being part of one table.

```
/* Search results table, used for search and filtered views of topics */
/* -- Temporary Solution until version 9 -- */

.dnn-community-forums .af-search-results .af-colstats {
	width: 3em;
}

.dnn-community-forums .af-search-results  .af-lastpost{
	width: 15em;
}
```

**Comment by johnhenley** [comment] 2024-07-02 11:40
@david-poindexter @Timo-Breumelhof this is duplicate of #656 I think. 

Expecting this view to get a makeover in v8.2 or v9 as we continue to move towards better html practices and moving from hard-coded to templates and resource strings for small snippets. 

I did a workaround on my site by adding this to the /themes/community-default/custom/theme.css (I LOVE that feature for layering in the custom CSS 😊) This kinda fixes it by adding this, but not really sure what I’m doing 😊
.afgrid {table-layout: fixed;}

**Comment by Timo-Breumelhof** [comment] 2024-07-02 12:26
@johnhenley try the CSS above ;-)

**Comment by david-poindexter** [comment] 2024-07-02 15:30
> @david-poindexter @Timo-Breumelhof this is duplicate of #656 I think.
> 
> Expecting this view to get a makeover in v8.2 or v9 as we continue to move towards better html practices and moving from hard-coded to templates and resource strings for small snippets.
> 
> I did a workaround on my site by adding this to the /themes/community-default/custom/theme.css (I LOVE that feature for layering in the custom CSS 😊) This kinda fixes it by adding this, but not really sure what I’m doing 😊 .afgrid {table-layout: fixed;}

My apologies for the duplicate - I somehow missed that.  🙂

**Closed** 2024-07-02 22:36 UTC
Labels: enhancement, themes, usability
