### ISSUE TITLE
`QUICK REPLY` results in unexpected error and doesn't post the comment

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/Dnn.CommunityForums#648] opened 2024-01-10 19:41 UTC
## Describe the bug
When posting a `QUICK REPLY` regardless of waiting 200 seconds.

## Software Versions
- DNN: 09.13.01
- Module: 08.00.00

## To Reproduce
1. Use `Add Reply` to post a comment on a forum thread.
2. Wait > 200 seconds
3. Use `QUICK REPLY` to attempt posting a comment on a forum thread.

## Expected behavior
Comment should be posted with no error.

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4568451/973f7503-d166-4548-a397-25702abf5768)

## Error log
I'm not sure about this one.  I was just trying to respond to a forum thread on the DNN Community site.

## Additional context
I don't know if it related to doing the above on a single thread or if this is across threads.  In my case, I was trying to post on the same thread.  My initial post via `Add Reply` was successful, but then I realized after posting that someone else had already provided the same information (it was lost in paging for me).  So I deleted the post made via `Add Reply`.  Then I tried to add a different comment via `QUICK REPLY`.  It resulted in the above error.  I waited > 200 seconds and attempted it again - same error.  I refreshed the page and attempted it again - same error.  I waited another 5 ish minutes and tried again - same error.

**Comment by johnhenley** [comment] 2024-01-10 19:46
Hi @david-poindexter thanks for reporting. @WillStrohl discovered this yesterday #639, we have it fixed and will is going to update the site this afternoon.

**Comment by WillStrohl** [comment] 2024-01-10 19:47
Duplicate of #641 & #639

**Comment by WillStrohl** [comment] 2024-01-10 19:47
Oh, and it's released and upgraded on the site.

**Closed by WillStrohl** 2024-01-10 19:47 UTC

**Comment by david-poindexter** [comment] 2024-01-10 19:56
Oh, sorry for the duplicate.  I tried to get clarity on Slack before submitting but thought it was best to report it just in case it was not known.

**Comment by johnhenley** [comment] 2024-01-10 19:58
> Oh, sorry for the duplicate. I tried to get clarity on Slack before submitting but thought it was best to report it just in case it was not known.

Hey, thanks for reporting it. More the merrier :)

**Comment by WillStrohl** [comment] 2024-01-10 20:01
Sorry, David.  I'm not always monitoring Slack.  This morning, I was monitoring the website.  😆

**Comment by david-poindexter** [comment] 2024-01-10 20:46
> Sorry, David. I'm not always monitoring Slack. This morning, I was monitoring the website. 😆

Oh no worries at all (it wasn't intended as a jab).  :)
