### ISSUE TITLE
View Attachment runs into critical error in DNN 9.10.2

### ISSUE THREAD

**Issue by anhconnoem** [DNNCommunity/Dnn.CommunityForums#136] opened 2022-07-29 15:15 UTC
## Software Versions
- DNN: 9.10.2
- Module: 6.6.0

## To Reproduce
1. Add New Topic with Attachment
2. Go to the Topic that just has been created
3. Click on the Attachments
4. Notice the error "A critical error has occurred. Please check the Admin Logs for further details.

## Expected behavior
Should be able to view attachments

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

## Additional context
![AF_Attachment](https://user-images.githubusercontent.com/90995164/181790069-d3cb75ff-d5fd-4657-af90-bbae21d2735f.PNG)
![AF_CriticalError](https://user-images.githubusercontent.com/90995164/181790072-586c98e6-e73f-4763-8d41-5b1856b0704d.PNG)
![AFViewingAttachment_AdminLog](https://user-images.githubusercontent.com/90995164/181790073-81b34cc4-6bf0-4515-b117-e2f2560fc83a.PNG)

**Comment by WillStrohl** [comment] 2022-07-29 17:15
Thank you for reporting this.  Is it different from the previous issue that was already fixed? 
https://github.com/DNNCommunity/Dnn.CommunityForums/issues/29

**Comment by anhconnoem** [comment] 2022-08-01 15:02
> Thank you for reporting this. Is it different from the previous issue that was already fixed? #29

Hi Will, I am not so sure. This is a fresh installation. We cannot view attachment in either post or in reply.

**Comment by anhconnoem** [comment] 2022-08-01 15:05
> Thank you for reporting this. Is it different from the previous issue that was already fixed? #29

Hi Will, thank you for your great contribution on the active forum module. I am not so sure this is related to #29 or not. This is Fresh installation. We cannot view attachment in post or reply.

**Comment by WillStrohl** [comment] 2022-08-01 15:39
Thank you for your update on this.  Sometimes, it's difficult for anyone to know with this module.  :)

**Comment by johnhenley** [comment] 2022-08-02 12:33
@WillStrohl this is duplicate of issue #59, which is fixed by PR #114. But since there hasn't been a release that includes that fix, that issue continues to be encountered.

**Comment by johnhenley** [comment] 2022-08-02 12:36
> > Thank you for reporting this. Is it different from the previous issue that was already fixed? #29
> 
> 
> 
> Hi Will, thank you for your great contribution on the active forum module. I am not so sure this is related to #29 or not. This is Fresh installation. We cannot view attachment in post or reply.

@anhconnoem do you have access to sql database for this install? If so, I can send you the sql to fix this.

**Comment by WillStrohl** [comment] 2022-08-02 17:55
Thanks for letting us know, @johnhenley  😁

**Comment by WillStrohl** [comment] 2022-08-02 17:56
We're going to mark this as a duplicate and close it since we've confirmed it's a duplicate.  Thanks still for logging this, @anhconnoem ...  We really appreciate it!  :)

**Closed by WillStrohl** 2022-08-02 17:56 UTC
Labels: duplicate

**Comment by anhconnoem** [comment] 2022-08-02 20:49
> > > Thank you for reporting this. Is it different from the previous issue that was already fixed? #29
> > 
> > 
> > Hi Will, thank you for your great contribution on the active forum module. I am not so sure this is related to #29 or not. This is Fresh installation. We cannot view attachment in post or reply.
> 
> @anhconnoem do you have access to sql database for this install? If so, I can send you the sql to fix this.

@johnhenley I was able to issue #59 and was able to follow the fix instruction from there. Thank you.
