### ISSUE TITLE
Post list containment off on single forum landing page

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/Dnn.CommunityForums#936] opened 2024-07-01 14:28 UTC
## Describe the bug
When you go to a single forum landing page, the containment of the post list is outside the bounds of page content.

## Software Versions
- DNN: 09.13.03
- Module: 08.01.00

## To Reproduce
1. Go to https://dnncommunity.org/forums/using-dnn/upgrading-dnn/
2. See post list containment issue

## Expected behavior
The list of posts should be contained within the normal page content width (as it is on the main forum page and single post pages.

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4568451/551eda75-bf15-42c4-abd2-2cc95d891509)

## Error log
n/a

## Additional context
n/a

**Comment by Timo-Breumelhof** [comment] 2024-07-01 16:52
@david-poindexter thank you for logging thins. I can reproduce it, I'll have a look.

**Comment by Timo-Breumelhof** [comment] 2024-07-01 17:27
On this page one can see the effect:

https://dnncommunity.org/forums/using-dnn/upgrading-dnn/

As soon as I remove this post from the HTML in the list, the issue is gone.

https://dnncommunity.org/forums/using-dnn/upgrading-dnn/upgrade-from-09-11-00-to-09-11-02/

So this is probably caused by this "word"

`DotNetNuke.Services.Install.UpgradeWizard.TelerikAntiForgeryTokenIsValid(Dictionary`

We need to add this for situations like this:

`word-break: break-all;`

Tested locally, seems to work fine

**Comment by Timo-Breumelhof** [comment] 2024-07-01 17:47
@david-poindexter should be fixed on the community site now.. (CTRL-F5 ?)

**Comment by david-poindexter** [comment] 2024-07-01 17:54
> @david-poindexter should be fixed on the community site now.. (CTRL-F5 ?)

Awesome - it worked after purging Cloudflare cache.  Thank you!

**Comment by WillStrohl** [comment] 2024-07-01 18:52
@Timo-Breumelhof @johnhenley Should I process this, or is it waiting on something?

**Comment by johnhenley** [comment] 2024-07-01 19:19
> @Timo-Breumelhof @johnhenley Should I process this, or is it waiting on something?
Go ahead. I think you can do the 8.1.1 release if you want to pull all the open ones (#944, #943, #942).

**Closed** 2024-07-01 20:06 UTC
Labels: bug, themes
