### ISSUE TITLE
SQL Error Viewing Forum Post Attachments

### ISSUE THREAD

**Issue by euclid-mark** [DNNCommunity/Dnn.CommunityForums#106] opened 2021-11-15 14:15 UTC
## Describe the bug
When a user uploads an attachment to a forum post it will upload to the server fine. However, when someone tries to download the attachment they receive a critical error. The event log gives the following error. Message:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

## Software Versions
- DNN: 09.09.01
- Module: 06.06.00

## To Reproduce
1. Attach a document to a forum post.
2. Click on the document to download the attachment
3. Error: 
Message:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

## Expected behavior
When clicking on an attached document the document should be downloaded.

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.
RawUrl:/DesktopModules/ActiveForums/viewer.aspx?portalid=55&amp;moduleid=20937&amp;attachmentid=46

Referrer:https://www.domain.org/Members-Only/Discussion-Resources/aft/1084/afpgj/2

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

ExceptionHash:/VFfOZMMg9MveQQqJsZTO0DUn/8=

Message:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

StackTrace:

InnerMessage:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

InnerStackTrace:

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(SqlConnection connection, SqlTransaction transaction, CommandType commandType, String commandText, SqlParameter[] commandParameters, SqlConnectionOwnership connectionOwnership)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, String spName, Object[] parameterValues)
   at DotNetNuke.Modules.ActiveForums.Data.AttachController.Get(Int32 attachmentId, Int32 fileId, Boolean withSecurity)
   at DotNetNuke.Modules.ActiveForums.af_viewer.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

## Additional context
This install was initially version 2 or 3 of ActiveForum that has been upgraded multiple times over the years.

**Comment by JanDr2** [comment] 2021-11-18 17:39
I can confirm this issue happens with DNN version 09.10.01 as well, with a clean install of ActiveForums version 06.06.00

**Comment by hismightiness** [comment] 2021-11-19 17:08
@euclid-mark Thank you for reporting this issue so thoroughly!  👍🏽

**Comment by johnhenley** [comment] 2022-02-07 21:23
This is a duplicate of #59, with pending pull request #114

**Closed** 2022-02-15 19:15 UTC
Labels: bug
