### ISSUE TITLE
BUG: Moderator Buttons not styled correctly

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#995] opened 2024-07-17 20:14 UTC
## Describe the bug

Moderator Buttons not styled correctly

## Software Versions
- DNN: 09.13.03
- Module: 08.01.02

## Expected behavior
Correct styling

## Screenshots
![image](https://github.com/user-attachments/assets/cbcee36d-5a1a-43e0-bd7f-c057ecadf424)

**Comment by Timo-Breumelhof** [comment] 2024-07-18 07:51
Hello @johnhenley thank you for logging this issue.
Unfortunately this is a duplicate of #969 
hehehe ;-)

**Comment by Timo-Breumelhof** [comment] 2024-07-18 07:54
@johnhenley I closed #969

**Comment by Timo-Breumelhof** [comment] 2024-07-18 08:23
@johnhenley see PR #1000

**Closed** 2024-07-18 11:32 UTC
Labels: bug
